language: python
install: pip install tox-travis
script: tox
stages:
  - name: test
  - name: build
    if: type = push AND branch = master
jobs:
  include:
    - stage: test
      python: 3.7
    - stage: test
      python: 3.8
    - stage: test
      python: 3.9
